name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Output Rust Version for debugging
        run: rustc --version
      - name: Install cargo-leptos
        run: cargo install cargo-leptos --version 0.3.7 --locked
      - name: Check WASM target
        run: rustup target list --installed
      - name: Check cargo-leptos
        run: cargo leptos --version

      - name: Check formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build Leptos app
        run: cargo leptos build --release





